#!/bin/sh

CONTROLLER_NAME=`hostname -s`
CONTROLLER_IP=$(getent ahostsv4 $CONTROLLER_NAME|tail -1|awk '{print $1}')
INTERNAL_IP=$(hostname -I | awk '{print $1}')
KUBERNETES_PUBLIC_ADDRESS=$INTERNAL_IP

ETCD_DIR=etc/etcd
ETCD_PKI_DIR=${ETCD_DIR}/pki

TOKEN=`uuidgen | tr -d '-'`
ETCD_CLUSTER_TOKEN="default-${TOKEN}" # this should be unique per cluster
ETCD_NAME=$(hostname --short)

ETCD_CERT_FILE=/${ETCD_PKI_DIR}/etcd.crt
ETCD_CERT_KEY_FILE=/${ETCD_PKI_DIR}/etcd.key
ETCD_PEER_CERT_FILE=/${ETCD_PKI_DIR}/etcd-peer.crt
ETCD_PEER_KEY_FILE=/${ETCD_PKI_DIR}/etcd-peer.key
ETCD_CA_FILE=/${ETCD_PKI_DIR}/ca.crt
ETCD_PEER_CA_FILE=/${ETCD_PKI_DIR}/ca.crt

if [ ! -f ${ETCD_DIR}/etcd.conf ]; then
    echo "Generate ${ETCD_DIR}/etcd.conf"

    cat >${ETCD_DIR}/etcd.conf <<EOF
# [member]
ETCD_NAME=${ETCD_NAME}
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
#ETCD_WAL_DIR=""
#ETCD_SNAPSHOT_COUNT="10000"
#ETCD_HEARTBEAT_INTERVAL="100"
#ETCD_ELECTION_TIMEOUT="1000"
ETCD_LISTEN_PEER_URLS="https://${INTERNAL_IP}:2380"
ETCD_LISTEN_CLIENT_URLS="https://${INTERNAL_IP}:2379,http://127.0.0.1:2379"
#ETCD_MAX_SNAPSHOTS="5"
#ETCD_MAX_WALS="5"
#ETCD_CORS=""
#
[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://${INTERNAL_IP}:2380"
# if you use different ETCD_NAME (e.g. test), set ETCD_INITIAL_CLUSTER value for this name, i.e. "test=http://..."
ETCD_INITIAL_CLUSTER="${CONTROLLER_NAME}=https://${CONTROLLER_IP}:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="${ETCD_CLUSTER_TOKEN}"
ETCD_ADVERTISE_CLIENT_URLS="https://${INTERNAL_IP}:2379"
#ETCD_DISCOVERY=""
#ETCD_DISCOVERY_SRV=""
#ETCD_DISCOVERY_FALLBACK="proxy"
#ETCD_DISCOVERY_PROXY=""
#ETCD_STRICT_RECONFIG_CHECK="false"
#ETCD_AUTO_COMPACTION_RETENTION="0"
#
#[proxy]
#ETCD_PROXY="off"
#ETCD_PROXY_FAILURE_WAIT="5000"
#ETCD_PROXY_REFRESH_INTERVAL="30000"
#ETCD_PROXY_DIAL_TIMEOUT="1000"
#ETCD_PROXY_WRITE_TIMEOUT="5000"
#ETCD_PROXY_READ_TIMEOUT="0"
#
#[security]
ETCD_CERT_FILE="${ETCD_CERT_FILE}"
ETCD_KEY_FILE="${ETCD_CERT_KEY_FILE}"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_TRUSTED_CA_FILE="${ETCD_CA_FILE}"
#ETCD_AUTO_TLS="false"
ETCD_PEER_CERT_FILE="${ETCD_PEER_CERT_FILE}"
ETCD_PEER_KEY_FILE="${ETCD_PEER_KEY_FILE}"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="${ETCD_CA_FILE}"
#ETCD_PEER_AUTO_TLS="false"
#
#[logging]
#ETCD_DEBUG="false"
# examples for -log-package-levels etcdserver=WARNING,security=DEBUG
#ETCD_LOG_PACKAGE_LEVELS=""

EOF
else
        echo "Skip ${ETCD_IDR}/etcd.conf"
fi
